# Load configuration from config.yaml
configfile: "config/config.yaml"

# Rule to run the R script with the path parameter
rule run_r_script:
    input:
        script = "epiestim_estimate_r.R"
    params:
        path = config["path"]
        out = config["out"]
    shell:
        """
        Rscript {input.script} --path={params.path} > {params.out}
        """
